// device-activation-portal-reactjs/src/components/customer/customer-detail.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import moment  from 'moment';
import Button from "@mui/material/Button";
import Table from '@mui/material/Table'

import { CustomerApi } from '../../generated/api'
import { AuthenticationComponent } from '../../shared/AuthenticationComponent'
import { DeviceList } from '../device/device-list'

function CustomerDetail()  {
   const navigate = useNavigate();
   const { id } = useParams();
   const [customer, setDetails] = useState({});
   
   useEffect(() => {
      new CustomerApi().customerDetailIdGet(id)
         .then(response => response.json())
         .then(result => {
            setDetails(result);
         });
   }, [])
   
   return (
      <div>
         <div>
         {
            (AuthenticationComponent.instance.hasRule('customer-update') && 
            <Button style={{ marginRight: '10px'}} onClick={() => navigate('edit')}>Aanpassen</Button>)             
         }
         </div>
         
         <div>
            <h3>Omgeving: { (customer.name)}</h3>
         </div>

         <Table>
            <tbody>
                  <tr>
                     <th>Code</th>
                     <td>{ customer.code }</td>
                  </tr>
                  <tr>
                     <th>Omschrijving</th>
                     <td>{ customer.description }</td>
                  </tr>
                  <tr>
                     <th>Server</th>
                     <td>{ customer.Server }</td>
                  </tr>
                  <tr>
                     <th>Gebruikte licenties</th>
                     <td>{customer.registeredDevices} / { customer.maxDevices}</td>
                  </tr>
                  <tr>
                     <th>Aangemaakt op</th>
                     <td>
                        {
                          customer && moment(customer.created).format('DD-MM-yyyy HH:mm')
                        }                        
                     </td>
                  </tr>
            </tbody>
         </Table>

         <hr/>
         <div>
         {
            (AuthenticationComponent.instance.hasRule('device-add') && 
            <Button style={{ marginRight: '10px'}} onClick={() => navigate('/device/new')}>Device toevoegen</Button>)
         }
         </div>
         <DeviceList devices={customer.devices} />
      </div>
   
   );
   
}
export default CustomerDetail;

// src/app/customer/customer-detail/customer-detail.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { CustomerService } from 'src/app/shared/api/customer.service';
import { CustomerDetailViewModel } from 'src/app/shared/model/customerDetailViewModel';

@Component({
  selector: 'app-customer-detail',
  templateUrl: './customer-detail.component.html',
  styleUrls: ['./customer-detail.component.css']
})
export class CustomerDetailComponent implements OnInit, OnDestroy {

  customer: CustomerDetailViewModel;
  private subscriptions: Subscription;

  constructor(
    private route: ActivatedRoute,
    private customerService: CustomerService) {
      this.subscriptions = new Subscription();
    }


  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  ngOnInit(): void {
    const customerId = +this.route.snapshot.params['id'];
    this.fetchData(customerId);
  }

  fetchData(customerId: number) {
    this.subscriptions.add( 
      this.customerService.customerDetailIdGet(customerId).subscribe(
        (data: CustomerDetailViewModel) => {
          this.customer = data;
        }
      )
    );
  }

  deleteCustomer() {
    //currently not implemented
    // this.subscriptions.add(
    //   this.customerService.
    // );
  }

}



<div *ngIf="customer">
    <div>
        <button 
            [requireRule]="'customer-update'" 
            [routerLink]="['edit']"
            class="btn btn-primary" 
            style="margin-right: 10px;">Aanpassen</button>
        <!-- <button
            [requireRule]="'customer-remove'" 
            class="btn btn-danger"
            (click)="deleteCustomer()"
             >Verwijderen</button> -->
    </div>
    <div>
        <h3>Omgeving: {{customer.name}}</h3>
    </div>

    <table>
        <tbody>
            <tr>
                <th>Code</th>
                <td>{{ customer.code }}</td>
            </tr>
            <tr>
                <th>Omschrijving</th>
                <td>{{ customer.description }}</td>
            </tr>
            <tr>
                <th>Server</th>
                <td>{{ customer.Server }}</td>
            </tr>
            <tr>
                <th>Gebruikte licenties</th>
                <td>{{customer.registeredDevices}} / {{ customer.maxDevices}}</td>
            </tr>
            <tr>
                <th>Aangemaakt op</th>
                <td>{{ customer.created | date: 'dd-MM-yyyy HH:mm' }}</td>
            </tr>
        </tbody>
    </table>

</div>    
<hr>
<div 
    *ngIf="customer"
    [requireRule]="'device-add'" 
    >
        <button 
        class="btn btn-primary"
        [disabled]="!customer.hasRemainingLicences"
        [routerLink]="['device', 'new']"
        (click)="addDevice()"
        style="margin-bottom: 15px;"
        >Device toevoegen</button>
</div>

<app-device-list *ngIf="customer"
    [customerId]="customer.id" 
    [devices]="customer.devices">
</app-device-list>
